# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: pytest-subprocess-ci

on:
  push:
    branches:
      - master

  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ${{ matrix.platform }}
    strategy:
      max-parallel: 4
      matrix:
        platform: [ ubuntu-latest, macos-latest, windows-latest ]
        python-version: [ 3.7, 3.8, 3.9, '3.10', '3.11' ]

    steps:
      - uses: actions/checkout@v2
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64
      - name: Setup Nox
        uses: aklajnert/setup-nox@v2.0.1
      - name: Run tests
        if: matrix.python-version != '3.11-dev'
        run: |
          nox -s tests-${{ matrix.python-version }} --error-on-missing-interpreters
        env:
          PLATFORM: ${{ matrix.platform }}
      - name: Run tests 3.11
        if: matrix.python-version == '3.11-dev'
        run: |
          nox -s tests-3.11 --error-on-missing-interpreters
        env:
          PLATFORM: ${{ matrix.platform }}
      - name: Update coverage
        uses: codecov/codecov-action@v1

  test-pypy:
    runs-on: ${{ matrix.platform }}
    strategy:
      max-parallel: 4
      matrix:
        platform: [ ubuntu-latest, macos-latest, windows-latest ]
        python-version: [ pypy-3.7 ]

    steps:
      - uses: actions/checkout@v2
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64
      - name: Setup Nox
        uses: aklajnert/setup-nox@v2.0.1
      - name: Run tests
        run: |
          nox -s tests-pypy3 --error-on-missing-interpreters
        env:
          PLATFORM: ${{ matrix.platform }}

  mypy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup Nox
        uses: aklajnert/setup-nox@v2.0.1
      - name: Run mypy
        run: |
          nox -s mypy
  flake8:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup Nox
        uses: aklajnert/setup-nox@v2.0.1
      - name: Run flake8
        run: |
          nox -s flake8
  check-docs:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup Nox
        uses: aklajnert/setup-nox@v2.0.1
      - name: Build docs
        run: |
          nox -s docs
