# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: pytest-subprocess-ci

on:
  push:
    branches:
      - master

  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ${{ matrix.platform }}
    strategy:
      max-parallel: 4
      matrix:
        platform: [ ubuntu-latest, macos-latest, windows-latest ]
        python-version: [ '3.8', '3.9', '3.10', '3.11', '3.12', '3.13', 'pypy3.8']

    steps:
      - uses: actions/checkout@v3
      - name: Setup Nox
        uses: wntrblm/nox@2024.10.09
        with:
          python-versions: ${{ matrix.python-version }}
      - name: Run tests
        run: |
          nox -s tests-${{ matrix.python-version }}
        env:
          PLATFORM: ${{ matrix.platform }}
      - name: Upload test results to Codecov
        if: ${{ !cancelled() }}
        uses: codecov/test-results-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
      - uses: codecov/codecov-action@v5
        if: matrix.python-version != 'pypy3.8'
        with:
          token: ${{ secrets.CODECOV_TOKEN }}


  mypy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup Nox
        uses: wntrblm/nox@2024.10.09
      - name: Run mypy
        run: |
          nox -s mypy
  flake8:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup Nox
        uses: wntrblm/nox@2024.10.09
      - name: Run flake8
        run: |
          nox -s flake8
  check-docs:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup Nox
        uses: wntrblm/nox@2024.10.09
      - name: Build docs
        run: |
          nox -s docs
