# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: pytest-subprocess-ci

on: [push, pull_request]

jobs:
  test:
    runs-on: ${{ matrix.platform }}
    strategy:
      max-parallel: 4
      matrix:
        platform: [ ubuntu-latest, macos-latest, windows-latest ]
        python-version: [ 3.6, 3.7, 3.8, 3.9, pypy-3.6, pypy-3.7 ]

    steps:
      - uses: actions/checkout@v2
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64
      - name: Setup Nox
        uses: excitedleigh/setup-nox@v2.0.0
      - uses: jungwinter/split@v1
        id: split
        with:
          msg: ${{ matrix.python-version }}
          seperator: "-"
      - name: Run tests
        run: |
          nox -s tests-${{ steps.split.outputs._0 }} --error-on-missing-interpreters
        env:
          PLATFORM: ${{ matrix.platform }}

  mypy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup Nox
        uses: excitedleigh/setup-nox@v2.0.0
      - name: Run mypy
        run: |
          nox -s mypy
  flake8:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup Nox
        uses: excitedleigh/setup-nox@v2.0.0
      - name: Run flake8
        run: |
          nox -s flake8
